import { SubNavBar } from '@/components/SubNavBar ';
import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  
}: {
  children: React.ReactNode;
}) {

  return (
      <body>
        <SubNavBar />
        {children}
      </body>
  );
}
