import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const opensans = Roboto({ subsets: ['cyrillic'], weight: ['100', '300', '400', '500', '700', '900']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={opensans.className}>
        {children}
      </body>
    </html>
  );
}
